"""Download the woff2 faces we use, trim the Latin ones, emit css/fonts.css.

Self-hosting removes two preconnects and a render-blocking stylesheet from the
critical path. Two further savings on top of that:

  - only the arabic and latin ranges are kept, and unicode-range means a page
    never downloads a range it does not render;
  - the Latin faces are re-subset to ASCII plus the punctuation this site uses.
    Google's Latin subset carries the whole European repertoire at about 29 KB
    a face; all we set in Latin is digits, tech names and English copy.

The Arabic faces are shipped exactly as Google built them. Trimming those to the
characters currently on the page would break the moment somebody edits the copy.

Re-run after any font change:  python _dev/fetch_fonts.py
"""

import io
import os
import re
import urllib.request

from fontTools import subset
from fontTools.ttLib import TTFont

UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
)

FAMILIES = [
    ("Alexandria", [400, 500, 600], {"arabic", "latin"}),
    ("Inter", [400, 500, 600], {"latin"}),
    ("IBM Plex Mono", [400, 500], {"latin"}),
]

# ASCII plus the punctuation and symbols the copy and the UI actually use
LATIN_CODEPOINTS = set(range(0x20, 0x7F)) | {
    0x00A0,  # no-break space
    0x00A9,  # copyright
    0x00D7,  # multiplication sign
    0x2013,  # en dash, in ranges
    0x2018, 0x2019,  # single quotes
    0x201C, 0x201D,  # double quotes
    0x2026,  # ellipsis
    0x20AC,  # euro
}

OUT_DIR = "assets/fonts"
os.makedirs(OUT_DIR, exist_ok=True)


def get(url):
    request = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(request, timeout=60) as response:
        return response.read()


def trim_to_latin(raw):
    """Re-subset a woff2 face down to LATIN_CODEPOINTS, keeping layout features."""
    source = io.BytesIO(raw)
    font = TTFont(source)
    options = subset.Options()
    options.flavor = "woff2"
    options.layout_features = ["*"]
    options.notdef_outline = True
    options.name_IDs = ["*"]
    options.name_legacy = True
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=LATIN_CODEPOINTS)
    subsetter.subset(font)
    out = io.BytesIO()
    font.flavor = "woff2"
    font.save(out)
    font.close()
    return out.getvalue()


blocks = []
total = 0

for family, weights, wanted in FAMILIES:
    css_url = (
        "https://fonts.googleapis.com/css2?family="
        + family.replace(" ", "+")
        + ":wght@"
        + ";".join(str(w) for w in weights)
        + "&display=swap"
    )
    css = get(css_url).decode("utf-8")
    faces = re.findall(r"/\*\s*([a-z0-9-]+)\s*\*/\s*@font-face\s*\{(.*?)\}", css, re.S)
    slug = family.lower().replace(" ", "-")

    for subset_name, body in faces:
        if subset_name not in wanted:
            continue
        weight = re.search(r"font-weight:\s*(\d+)", body).group(1)
        src = re.search(r"url\((https://[^)]+\.woff2)\)", body).group(1)
        rng = re.search(r"unicode-range:\s*([^;]+);", body).group(1).strip()

        raw = get(src)
        before = len(raw)
        if subset_name == "latin":
            raw = trim_to_latin(raw)
            rng = "U+0000-00FF, U+2013, U+2018-2019, U+201C-201D, U+2026, U+20AC"

        name = f"{slug}-{weight}-{subset_name}.woff2"
        with open(os.path.join(OUT_DIR, name), "wb") as handle:
            handle.write(raw)
        total += len(raw)
        note = f"  (from {before/1024:.0f} KB)" if len(raw) != before else ""
        print(f"  {name:34s} {len(raw)/1024:6.1f} KB{note}")

        blocks.append(
            "@font-face {\n"
            f"  font-family: '{family}';\n"
            "  font-style: normal;\n"
            f"  font-weight: {weight};\n"
            "  font-display: swap;\n"
            f"  src: url('../assets/fonts/{name}') format('woff2');\n"
            f"  unicode-range: {rng};\n"
            "}"
        )

header = (
    "/* ==========================================================================\n"
    "   بوابتك - Self-hosted faces\n"
    "   Generated by _dev/fetch_fonts.py. Arabic ranges ship as Google built them;\n"
    "   Latin ranges are re-subset to ASCII plus the punctuation this site uses.\n"
    "   Do not edit by hand, re-run the script.\n"
    "   ========================================================================== */\n"
)

io.open("css/fonts.css", "w", encoding="utf-8").write(
    header + "\n" + "\n\n".join(blocks) + "\n"
)
print(f"\n{len(blocks)} faces, {total/1024:.0f} KB total -> css/fonts.css")
